// AI-Powered Project Builder
// Analyzes requirements and generates complete multi-file projects

import { ProjectStructure, ProjectFile } from './project-generator';

export interface BuilderRequest {
  projectName: string;
  description: string;
  templateId?: string;
  features: string[];
  includeAuth: boolean;
  includeDatabase: boolean;
  databaseTables?: DatabaseTable[];
  pages: PageDefinition[];
  apiEndpoints?: APIEndpoint[];
  styling: 'tailwind' | 'css' | 'styled-components';
}

export interface DatabaseTable {
  name: string;
  columns: {
    name: string;
    type: 'text' | 'integer' | 'boolean' | 'timestamp' | 'uuid' | 'jsonb';
    nullable?: boolean;
    unique?: boolean;
    defaultValue?: string;
    references?: { table: string; column: string };
  }[];
  enableRLS: boolean;
}

export interface PageDefinition {
  path: string;
  name: string;
  type: 'page' | 'layout' | 'loading' | 'error';
  components: string[];
  requiresAuth: boolean;
  dataFetching?: 'server' | 'client' | 'static';
}

export interface APIEndpoint {
  path: string;
  methods: ('GET' | 'POST' | 'PUT' | 'DELETE')[];
  description: string;
  requiresAuth: boolean;
  database?: {
    table: string;
    operations: ('select' | 'insert' | 'update' | 'delete')[];
  };
}

// Generate Supabase SQL schema from table definitions
export function generateSupabaseSchema(tables: DatabaseTable[]): string {
  let sql = '-- Supabase Schema\n-- Generated by SolveIt Pro Builder\n\n';
  
  // Enable UUID extension
  sql += '-- Enable UUID extension\nCREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n';
  
  for (const table of tables) {
    sql += `-- Table: ${table.name}\n`;
    sql += `CREATE TABLE IF NOT EXISTS ${table.name} (\n`;
    
    const columnDefs: string[] = [];
    
    // Add id column by default
    columnDefs.push('  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY');
    
    for (const col of table.columns) {
      let def = `  ${col.name} `;
      
      // Map types
      switch (col.type) {
        case 'text': def += 'TEXT'; break;
        case 'integer': def += 'INTEGER'; break;
        case 'boolean': def += 'BOOLEAN'; break;
        case 'timestamp': def += 'TIMESTAMPTZ'; break;
        case 'uuid': def += 'UUID'; break;
        case 'jsonb': def += 'JSONB'; break;
      }
      
      if (!col.nullable) def += ' NOT NULL';
      if (col.unique) def += ' UNIQUE';
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      if (col.references) {
        def += ` REFERENCES ${col.references.table}(${col.references.column}) ON DELETE CASCADE`;
      }
      
      columnDefs.push(def);
    }
    
    // Add timestamps
    columnDefs.push('  created_at TIMESTAMPTZ DEFAULT NOW()');
    columnDefs.push('  updated_at TIMESTAMPTZ DEFAULT NOW()');
    
    sql += columnDefs.join(',\n');
    sql += '\n);\n\n';
    
    // Add RLS policies if enabled
    if (table.enableRLS) {
      sql += `-- Enable RLS for ${table.name}\n`;
      sql += `ALTER TABLE ${table.name} ENABLE ROW LEVEL SECURITY;\n\n`;
      sql += `-- Policy: Users can view their own data\n`;
      sql += `CREATE POLICY "${table.name}_select_own" ON ${table.name}\n`;
      sql += `  FOR SELECT USING (auth.uid() = user_id);\n\n`;
      sql += `-- Policy: Users can insert their own data\n`;
      sql += `CREATE POLICY "${table.name}_insert_own" ON ${table.name}\n`;
      sql += `  FOR INSERT WITH CHECK (auth.uid() = user_id);\n\n`;
      sql += `-- Policy: Users can update their own data\n`;
      sql += `CREATE POLICY "${table.name}_update_own" ON ${table.name}\n`;
      sql += `  FOR UPDATE USING (auth.uid() = user_id);\n\n`;
      sql += `-- Policy: Users can delete their own data\n`;
      sql += `CREATE POLICY "${table.name}_delete_own" ON ${table.name}\n`;
      sql += `  FOR DELETE USING (auth.uid() = user_id);\n\n`;
    }
    
    // Add updated_at trigger
    sql += `-- Trigger for updated_at\n`;
    sql += `CREATE OR REPLACE FUNCTION update_${table.name}_updated_at()\n`;
    sql += `RETURNS TRIGGER AS $$\n`;
    sql += `BEGIN\n`;
    sql += `  NEW.updated_at = NOW();\n`;
    sql += `  RETURN NEW;\n`;
    sql += `END;\n`;
    sql += `$$ LANGUAGE plpgsql;\n\n`;
    sql += `CREATE TRIGGER ${table.name}_updated_at_trigger\n`;
    sql += `  BEFORE UPDATE ON ${table.name}\n`;
    sql += `  FOR EACH ROW\n`;
    sql += `  EXECUTE FUNCTION update_${table.name}_updated_at();\n\n`;
  }
  
  return sql;
}

// Generate API route for a table
export function generateAPIRoute(endpoint: APIEndpoint, table?: DatabaseTable): string {
  const hasGet = endpoint.methods.includes('GET');
  const hasPost = endpoint.methods.includes('POST');
  const hasPut = endpoint.methods.includes('PUT');
  const hasDelete = endpoint.methods.includes('DELETE');
  
  let code = `import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@/lib/supabase';
${endpoint.requiresAuth ? "import { getSession } from '@/lib/supabase';" : ''}

`;

  if (hasGet) {
    code += `// GET - ${endpoint.description}
export async function GET(request: NextRequest) {
  try {
    ${endpoint.requiresAuth ? `
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    ` : ''}
    const supabase = createServerClient();
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    let query = supabase.from('${endpoint.database?.table || 'items'}').select('*');
    
    if (id) {
      query = query.eq('id', id).single();
    }
    ${endpoint.requiresAuth ? "\n    query = query.eq('user_id', session.user.id);" : ''}
    
    const { data, error } = await query;
    
    if (error) throw error;
    
    return NextResponse.json({ data });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

`;
  }

  if (hasPost) {
    code += `// POST - Create new ${endpoint.database?.table || 'item'}
export async function POST(request: NextRequest) {
  try {
    ${endpoint.requiresAuth ? `
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    ` : ''}
    const supabase = createServerClient();
    const body = await request.json();
    
    const { data, error } = await supabase
      .from('${endpoint.database?.table || 'items'}')
      .insert([{ ...body${endpoint.requiresAuth ? ", user_id: session.user.id" : ''} }])
      .select()
      .single();
    
    if (error) throw error;
    
    return NextResponse.json({ data }, { status: 201 });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

`;
  }

  if (hasPut) {
    code += `// PUT - Update ${endpoint.database?.table || 'item'}
export async function PUT(request: NextRequest) {
  try {
    ${endpoint.requiresAuth ? `
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    ` : ''}
    const supabase = createServerClient();
    const body = await request.json();
    const { id, ...updateData } = body;
    
    if (!id) {
      return NextResponse.json({ error: 'ID is required' }, { status: 400 });
    }
    
    let query = supabase
      .from('${endpoint.database?.table || 'items'}')
      .update(updateData)
      .eq('id', id);
    ${endpoint.requiresAuth ? "\n    query = query.eq('user_id', session.user.id);" : ''}
    
    const { data, error } = await query.select().single();
    
    if (error) throw error;
    
    return NextResponse.json({ data });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

`;
  }

  if (hasDelete) {
    code += `// DELETE - Delete ${endpoint.database?.table || 'item'}
export async function DELETE(request: NextRequest) {
  try {
    ${endpoint.requiresAuth ? `
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    ` : ''}
    const supabase = createServerClient();
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json({ error: 'ID is required' }, { status: 400 });
    }
    
    let query = supabase
      .from('${endpoint.database?.table || 'items'}')
      .delete()
      .eq('id', id);
    ${endpoint.requiresAuth ? "\n    query = query.eq('user_id', session.user.id);" : ''}
    
    const { error } = await query;
    
    if (error) throw error;
    
    return NextResponse.json({ success: true });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
`;
  }

  return code;
}

// Generate a React hook for data fetching
export function generateDataHook(tableName: string): string {
  const capitalName = tableName.charAt(0).toUpperCase() + tableName.slice(1);
  
  return `import { useState, useEffect, useCallback } from 'react';

interface ${capitalName}Item {
  id: string;
  [key: string]: any;
}

interface Use${capitalName}Return {
  data: ${capitalName}Item[];
  loading: boolean;
  error: string | null;
  refetch: () => Promise<void>;
  create: (item: Partial<${capitalName}Item>) => Promise<${capitalName}Item | null>;
  update: (id: string, item: Partial<${capitalName}Item>) => Promise<${capitalName}Item | null>;
  remove: (id: string) => Promise<boolean>;
}

export function use${capitalName}(): Use${capitalName}Return {
  const [data, setData] = useState<${capitalName}Item[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await fetch('/api/${tableName}');
      const json = await res.json();
      
      if (!res.ok) throw new Error(json.error);
      
      setData(json.data || []);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const create = async (item: Partial<${capitalName}Item>) => {
    try {
      const res = await fetch('/api/${tableName}', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(item),
      });
      const json = await res.json();
      
      if (!res.ok) throw new Error(json.error);
      
      setData(prev => [...prev, json.data]);
      return json.data;
    } catch (err: any) {
      setError(err.message);
      return null;
    }
  };

  const update = async (id: string, item: Partial<${capitalName}Item>) => {
    try {
      const res = await fetch('/api/${tableName}', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id, ...item }),
      });
      const json = await res.json();
      
      if (!res.ok) throw new Error(json.error);
      
      setData(prev => prev.map(d => d.id === id ? json.data : d));
      return json.data;
    } catch (err: any) {
      setError(err.message);
      return null;
    }
  };

  const remove = async (id: string) => {
    try {
      const res = await fetch(\`/api/${tableName}?id=\${id}\`, {
        method: 'DELETE',
      });
      
      if (!res.ok) {
        const json = await res.json();
        throw new Error(json.error);
      }
      
      setData(prev => prev.filter(d => d.id !== id));
      return true;
    } catch (err: any) {
      setError(err.message);
      return false;
    }
  };

  return { data, loading, error, refetch: fetchData, create, update, remove };
}
`;
}

// Generate auth context
export function generateAuthContext(): string {
  return `'use client';

import { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { User, Session } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';

interface AuthContextType {
  user: User | null;
  session: Session | null;
  loading: boolean;
  signIn: (email: string, password: string) => Promise<{ error: any }>;
  signUp: (email: string, password: string) => Promise<{ error: any }>;
  signOut: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Get initial session
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
      setUser(session?.user ?? null);
      setLoading(false);
    });

    // Listen for auth changes
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        setSession(session);
        setUser(session?.user ?? null);
        setLoading(false);
      }
    );

    return () => subscription.unsubscribe();
  }, []);

  const signIn = async (email: string, password: string) => {
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    return { error };
  };

  const signUp = async (email: string, password: string) => {
    const { error } = await supabase.auth.signUp({ email, password });
    return { error };
  };

  const signOut = async () => {
    await supabase.auth.signOut();
  };

  return (
    <AuthContext.Provider value={{ user, session, loading, signIn, signUp, signOut }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}
`;
}

// Generate a protected route wrapper
export function generateProtectedRoute(): string {
  return `'use client';

import { useAuth } from '@/contexts/AuthContext';
import { useRouter } from 'next/navigation';
import { useEffect, ReactNode } from 'react';

interface ProtectedRouteProps {
  children: ReactNode;
  fallback?: ReactNode;
}

export function ProtectedRoute({ children, fallback }: ProtectedRouteProps) {
  const { user, loading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && !user) {
      router.push('/login');
    }
  }, [user, loading, router]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary-500"></div>
      </div>
    );
  }

  if (!user) {
    return fallback || null;
  }

  return <>{children}</>;
}
`;
}

// Generate login page
export function generateLoginPage(): string {
  return `'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import Link from 'next/link';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { signIn } = useAuth();
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const { error } = await signIn(email, password);
      if (error) throw error;
      router.push('/dashboard');
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900 dark:text-white">
            Sign in to your account
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600 dark:text-gray-400">
            Or{' '}
            <Link href="/register" className="font-medium text-primary-600 hover:text-primary-500">
              create a new account
            </Link>
          </p>
        </div>
        
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 dark:bg-red-900/50 text-red-500 p-3 rounded-lg text-sm">
              {error}
            </div>
          )}
          
          <div className="rounded-md shadow-sm space-y-4">
            <div>
              <label htmlFor="email" className="sr-only">Email address</label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="input"
                placeholder="Email address"
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">Password</label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="input"
                placeholder="Password"
              />
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                id="remember-me"
                name="remember-me"
                type="checkbox"
                className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
              />
              <label htmlFor="remember-me" className="ml-2 block text-sm text-gray-900 dark:text-gray-300">
                Remember me
              </label>
            </div>

            <div className="text-sm">
              <Link href="/forgot-password" className="font-medium text-primary-600 hover:text-primary-500">
                Forgot your password?
              </Link>
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full btn-primary py-3 flex justify-center"
          >
            {loading ? (
              <div className="animate-spin rounded-full h-5 w-5 border-t-2 border-b-2 border-white"></div>
            ) : (
              'Sign in'
            )}
          </button>
        </form>
      </div>
    </div>
  );
}
`;
}

// Generate register page
export function generateRegisterPage(): string {
  return `'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import Link from 'next/link';

export default function RegisterPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const { signUp } = useAuth();
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (password !== confirmPassword) {
      setError('Passwords do not match');
      return;
    }

    if (password.length < 6) {
      setError('Password must be at least 6 characters');
      return;
    }

    setLoading(true);

    try {
      const { error } = await signUp(email, password);
      if (error) throw error;
      setSuccess(true);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (success) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4">
        <div className="max-w-md w-full text-center">
          <div className="text-6xl mb-4">📧</div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
            Check your email
          </h2>
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            We sent a confirmation link to <strong>{email}</strong>
          </p>
          <Link href="/login" className="btn-primary inline-block">
            Back to login
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900 dark:text-white">
            Create your account
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600 dark:text-gray-400">
            Already have an account?{' '}
            <Link href="/login" className="font-medium text-primary-600 hover:text-primary-500">
              Sign in
            </Link>
          </p>
        </div>
        
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 dark:bg-red-900/50 text-red-500 p-3 rounded-lg text-sm">
              {error}
            </div>
          )}
          
          <div className="rounded-md shadow-sm space-y-4">
            <div>
              <label htmlFor="email" className="sr-only">Email address</label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="input"
                placeholder="Email address"
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">Password</label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="new-password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="input"
                placeholder="Password (min 6 characters)"
              />
            </div>
            <div>
              <label htmlFor="confirm-password" className="sr-only">Confirm Password</label>
              <input
                id="confirm-password"
                name="confirm-password"
                type="password"
                autoComplete="new-password"
                required
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                className="input"
                placeholder="Confirm password"
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full btn-primary py-3 flex justify-center"
          >
            {loading ? (
              <div className="animate-spin rounded-full h-5 w-5 border-t-2 border-b-2 border-white"></div>
            ) : (
              'Create account'
            )}
          </button>
        </form>
      </div>
    </div>
  );
}
`;
}

// Export project as downloadable files structure
export function generateProjectExport(project: ProjectStructure): { filename: string; content: string }[] {
  return project.files.map(f => ({
    filename: f.path,
    content: f.content
  }));
}
