// Export templates for different project types

import { PageData } from './types';

interface ExportFiles {
  [filename: string]: string;
}

// Helper to escape backticks in template content
const codeBlock = (lang: string, code: string) => '```' + lang + '\n' + code + '\n```';

export function generateHtmlExport(pages: PageData[], projectName: string): ExportFiles {
  const files: ExportFiles = {};
  
  pages.forEach((page) => {
    const fileName = page.name.toLowerCase().replace(/\s+/g, '-') + '.html';
    files[fileName] = page.content;
  });

  // Add a simple index if multiple pages
  if (pages.length > 1) {
    const links = pages.map(p => {
      const fileName = p.name.toLowerCase().replace(/\s+/g, '-') + '.html';
      return '<li><a href="' + fileName + '">' + p.name + '</a></li>';
    }).join('\n      ');

    files['index.html'] = '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>' + projectName + '</title>\n  <style>\n    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }\n    h1 { color: #333; }\n    ul { list-style: none; padding: 0; }\n    li { margin: 10px 0; }\n    a { color: #0066cc; text-decoration: none; font-size: 18px; }\n    a:hover { text-decoration: underline; }\n  </style>\n</head>\n<body>\n  <h1>' + projectName + '</h1>\n  <h2>Pages</h2>\n  <ul>\n    ' + links + '\n  </ul>\n</body>\n</html>';
  }

  // README
  files['README.md'] = '# ' + projectName + '\n\nGenerated by **Solve It!** 🚀\n\n## Pages\n\n' + pages.map(p => '- ' + p.name).join('\n');

  return files;
}

export function generateReactExport(pages: PageData[], projectName: string): ExportFiles {
  const files: ExportFiles = {};

  // package.json
  files['package.json'] = JSON.stringify({
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'react-scripts start',
      build: 'react-scripts build',
      test: 'react-scripts test',
      eject: 'react-scripts eject'
    },
    dependencies: {
      'react': '^18.2.0',
      'react-dom': '^18.2.0',
      'react-scripts': '5.0.1',
      'react-router-dom': '^6.8.0'
    },
    browserslist: {
      production: ['>0.2%', 'not dead', 'not op_mini all'],
      development: ['last 1 chrome version', 'last 1 firefox version', 'last 1 safari version']
    }
  }, null, 2);

  // public/index.html
  files['public/index.html'] = '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1" />\n  <title>' + projectName + '</title>\n</head>\n<body>\n  <noscript>You need to enable JavaScript to run this app.</noscript>\n  <div id="root"></div>\n</body>\n</html>';

  // src/index.js
  files['src/index.js'] = "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nconst root = ReactDOM.createRoot(document.getElementById('root'));\nroot.render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);";

  // src/index.css
  files['src/index.css'] = '* { margin: 0; padding: 0; box-sizing: border-box; }\nbody { font-family: system-ui, -apple-system, sans-serif; }';

  // src/App.js with routing
  const routes = pages.map((page, i) => {
    const path = i === 0 ? '/' : '/' + page.name.toLowerCase().replace(/\s+/g, '-');
    const component = page.name.replace(/\s+/g, '');
    return '        <Route path="' + path + '" element={<' + component + ' />} />';
  }).join('\n');

  const imports = pages.map(page => {
    const component = page.name.replace(/\s+/g, '');
    return "import " + component + " from './pages/" + component + "';";
  }).join('\n');

  files['src/App.js'] = "import { BrowserRouter, Routes, Route } from 'react-router-dom';\n" + imports + "\n\nfunction App() {\n  return (\n    <BrowserRouter>\n      <Routes>\n" + routes + "\n      </Routes>\n    </BrowserRouter>\n  );\n}\n\nexport default App;";

  // Create page components
  pages.forEach(page => {
    const component = page.name.replace(/\s+/g, '');
    const content = convertHtmlToReact(page.content, page.name);
    files['src/pages/' + component + '.js'] = content;
  });

  // README
  files['README.md'] = '# ' + projectName + '\n\nGenerated by **Solve It!** 🚀\n\n## Getting Started\n\n' + codeBlock('bash', 'npm install\nnpm start') + '\n\n## Pages\n\n' + pages.map(p => '- ' + p.name).join('\n');

  return files;
}

export function generateNextExport(pages: PageData[], projectName: string): ExportFiles {
  const files: ExportFiles = {};

  // package.json
  files['package.json'] = JSON.stringify({
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      'next': '^14.0.0',
      'react': '^18.2.0',
      'react-dom': '^18.2.0'
    },
    devDependencies: {
      '@types/node': '^20.0.0',
      '@types/react': '^18.2.0',
      'typescript': '^5.0.0'
    }
  }, null, 2);

  // next.config.js
  files['next.config.js'] = "/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  reactStrictMode: true,\n};\n\nmodule.exports = nextConfig;";

  // tsconfig.json
  files['tsconfig.json'] = JSON.stringify({
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      paths: { '@/*': ['./src/*'] }
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules']
  }, null, 2);

  // src/app/layout.tsx
  files['src/app/layout.tsx'] = "import type { Metadata } from 'next';\nimport './globals.css';\n\nexport const metadata: Metadata = {\n  title: '" + projectName + "',\n  description: 'Generated by Solve It!',\n};\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode;\n}) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}";

  // src/app/globals.css
  files['src/app/globals.css'] = '* { margin: 0; padding: 0; box-sizing: border-box; }\nbody { font-family: system-ui, -apple-system, sans-serif; }';

  // Convert pages to Next.js components
  pages.forEach((page, index) => {
    const isHome = index === 0 || page.name.toLowerCase() === 'home' || page.name.toLowerCase() === 'index';
    const pagePath = isHome ? 'src/app/page.tsx' : 'src/app/' + page.name.toLowerCase() + '/page.tsx';
    
    // Extract body content and convert to React component
    const componentContent = convertHtmlToReact(page.content, page.name);
    files[pagePath] = componentContent;
  });

  // README.md
  files['README.md'] = '# ' + projectName + '\n\nGenerated by **Solve It!** 🚀\n\n## Getting Started\n\n' + codeBlock('bash', 'npm install\nnpm run dev') + '\n\nOpen [http://localhost:3000](http://localhost:3000)\n\n## Pages\n\n' + pages.map(p => '- ' + p.name).join('\n');

  return files;
}

export function generateVueExport(pages: PageData[], projectName: string): ExportFiles {
  const files: ExportFiles = {};

  // package.json
  files['package.json'] = JSON.stringify({
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: {
      'vue': '^3.3.0',
      'vue-router': '^4.2.0'
    },
    devDependencies: {
      '@vitejs/plugin-vue': '^4.0.0',
      'vite': '^5.0.0'
    }
  }, null, 2);

  // vite.config.js
  files['vite.config.js'] = "import { defineConfig } from 'vite';\nimport vue from '@vitejs/plugin-vue';\n\nexport default defineConfig({\n  plugins: [vue()],\n});";

  // index.html
  files['index.html'] = '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>' + projectName + '</title>\n</head>\n<body>\n  <div id="app"></div>\n  <script type="module" src="/src/main.js"></script>\n</body>\n</html>';

  // src/main.js
  files['src/main.js'] = "import { createApp } from 'vue';\nimport App from './App.vue';\nimport router from './router';\nimport './style.css';\n\ncreateApp(App).use(router).mount('#app');";

  // src/style.css
  files['src/style.css'] = '* { margin: 0; padding: 0; box-sizing: border-box; }\nbody { font-family: system-ui, -apple-system, sans-serif; }';

  // src/App.vue
  files['src/App.vue'] = '<template>\n  <router-view />\n</template>\n\n<script setup>\n</script>';

  // src/router/index.js
  const routes = pages.map((page, i) => {
    const path = i === 0 ? '/' : '/' + page.name.toLowerCase().replace(/\s+/g, '-');
    const name = page.name.replace(/\s+/g, '');
    return "  { path: '" + path + "', name: '" + name + "', component: () => import('../views/" + name + ".vue') }";
  }).join(',\n');

  files['src/router/index.js'] = "import { createRouter, createWebHistory } from 'vue-router';\n\nconst routes = [\n" + routes + "\n];\n\nconst router = createRouter({\n  history: createWebHistory(),\n  routes,\n});\n\nexport default router;";

  // Create view components
  pages.forEach(page => {
    const name = page.name.replace(/\s+/g, '');
    const content = convertHtmlToVue(page.content, page.name);
    files['src/views/' + name + '.vue'] = content;
  });

  // README
  files['README.md'] = '# ' + projectName + '\n\nGenerated by **Solve It!** 🚀\n\n## Getting Started\n\n' + codeBlock('bash', 'npm install\nnpm run dev') + '\n\n## Pages\n\n' + pages.map(p => '- ' + p.name).join('\n');

  return files;
}

// Helper function to convert HTML to React component
function convertHtmlToReact(html: string, pageName: string): string {
  // Extract body content
  let content = html;
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*)<\/body>/i);
  if (bodyMatch) {
    content = bodyMatch[1];
  }

  // Extract styles
  let styles = '';
  const styleMatch = html.match(/<style[^>]*>([\s\S]*?)<\/style>/gi);
  if (styleMatch) {
    styles = styleMatch.map(s => s.replace(/<\/?style[^>]*>/gi, '')).join('\n');
  }

  const componentName = pageName.replace(/\s+/g, '');

  return "export default function " + componentName + "() {\n  return (\n    <>\n      " + (styles ? '<style>{`' + styles + '`}</style>' : '') + "\n      <div dangerouslySetInnerHTML={{ __html: `" + content.replace(/`/g, '\\`').replace(/\$/g, '\\$') + "` }} />\n    </>\n  );\n}";
}

// Helper function to convert HTML to Vue component
function convertHtmlToVue(html: string, pageName: string): string {
  // Extract body content
  let content = html;
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*)<\/body>/i);
  if (bodyMatch) {
    content = bodyMatch[1];
  }

  // Extract styles
  let styles = '';
  const styleMatch = html.match(/<style[^>]*>([\s\S]*?)<\/style>/gi);
  if (styleMatch) {
    styles = styleMatch.map(s => s.replace(/<\/?style[^>]*>/gi, '')).join('\n');
  }

  return '<template>\n  <div v-html="content"></div>\n</template>\n\n<script setup>\nconst content = `' + content.replace(/`/g, '\\`') + '`;\n</script>\n\n<style scoped>\n' + styles + '\n</style>';
}

// Export as JSON (for import/export feature)
export function exportAsJson(pages: PageData[], projectName: string, settings: any = {}): string {
  return JSON.stringify({
    name: projectName,
    version: '1.0.0',
    exportedAt: new Date().toISOString(),
    pages,
    settings
  }, null, 2);
}

// Import from JSON
export function importFromJson(jsonString: string): { pages: PageData[], projectName: string, settings: any } | null {
  try {
    const data = JSON.parse(jsonString);
    return {
      pages: data.pages || [],
      projectName: data.name || 'Imported Project',
      settings: data.settings || {}
    };
  } catch {
    return null;
  }
}
